server:
  port: 8001
spring:
  application:
    name: BBMALL-PLAT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #这是提供的服务 注册到eureka服务器上
  instance:
    instance-id: bbmall-plat-8001.com #为当前服务器添加实例的标识
    prefer-ip-address: true