server:
  port: 1299
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: bbmall-config-server:1299.com
    prefer-ip-address: true
spring:
  #profiles:
    #active: native #读取本地配置
  application:
    name: BBMALL-CONFIG-SERVER
  cloud:
    config:
      server:
        #native:
          #search-locations: E:/program/github/bbmall-config #本地配置所在的目录
        git:
          #https://github.com/yaohao/bbmall-config.git
          uri: https://github.com/yaohao123456/bbmall-config.git
          username: yaohao123456
          password: QWERqwer110