server:
  port: 1314
spring:
  application:
    name: BBMALL-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #将网关配置到eureka服务器上
  instance:
    instance-id: bbmall-zuul-gateway-1314.com #eureka服务器上status显示
    prefer-ip-address: true #eureka页面左下角显示ip
zuul:
  ignored-services: "*" #用*来通配符，忽略从1314端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:
    plat:
      path: /plat/**
      service-id: bbmall-plat